#!/bin/bash
# ============================================================
# Spevino Loss Prevention OS — One-Command Installer
# ============================================================
# Usage: curl -fsSL https://github.com/spevino/spevino-lpos/raw/main/install.sh | bash
#
# Or:  wget -qO- https://github.com/spevino/spevino-lpos/raw/main/install.sh | bash
#
# Installs: Docker, Docker Compose, clones the repo, 
# configures environment, and starts all services.
# ============================================================

set -e

VERSION="1.0.0"
REPO="spevino/spevino-lpos"
REPO_URL="https://github.com/$REPO"
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════╗"
echo "║     Spevino Loss Prevention OS Installer      ║"
echo "║           v$VERSION - One-Click Setup           ║"
echo "╚═══════════════════════════════════════════════╝"
echo -e "${NC}"

# --- Check OS ---
OS="$(uname -s)"
ARCH="$(uname -m)"
echo -e "${GREEN}✓${NC} Detected: $OS $ARCH"

# --- Install Docker if missing ---
if ! command -v docker &> /dev/null; then
    echo -e "${YELLOW}⚡${NC} Installing Docker..."
    curl -fsSL https://get.docker.com | bash
    sudo usermod -aG docker $USER
    echo -e "${GREEN}✓${NC} Docker installed"
else
    echo -e "${GREEN}✓${NC} Docker $(docker --version | cut -d' ' -f3 | tr -d ',')"
fi

# --- Install Docker Compose if missing ---
if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null; then
    echo -e "${YELLOW}⚡${NC} Installing Docker Compose..."
    sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
fi
echo -e "${GREEN}✓${NC} Docker Compose ready"

# --- Clone repo ---
INSTALL_DIR="/opt/spevino"
if [ -d "$INSTALL_DIR" ]; then
    echo -e "${YELLOW}⚡${NC} Updating existing installation at $INSTALL_DIR..."
    cd "$INSTALL_DIR"
    git pull
else
    echo -e "${YELLOW}⚡${NC} Cloning Spevino LP-OS..."
    sudo git clone "https://github.com/$REPO.git" "$INSTALL_DIR"
    sudo chown -R $USER:$USER "$INSTALL_DIR"
    cd "$INSTALL_DIR"
fi
echo -e "${GREEN}✓${NC} Repository cloned to $INSTALL_DIR"

# --- Setup .env ---
if [ ! -f "$INSTALL_DIR/.env" ]; then
    echo -e "${YELLOW}⚡${NC} Creating .env configuration..."
    
    # Generate secure random values
    JWT_SECRET=$(openssl rand -hex 32 2>/dev/null || date +%s | sha256sum | head -c 64)
    
    cat > "$INSTALL_DIR/.env" << EOF
# Spevino LP-OS Configuration
# Generated by installer on $(date)

# --- License ---
# Get your license key at https://spevino.com/license
# Without a license, the system runs in 14-day trial mode
LICENSE_KEY=

# --- JWT Authentication ---
JWT_SECRET_KEY=$JWT_SECRET
JWT_ALGORITHM=HS256

# --- Database ---
DATABASE_URL=sqlite:///data/spevino.db

# --- SMS (Optional — leave blank for mock mode) ---
# Sign up at https://twilio.com for SMS alerts
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_PHONE_NUMBER=

# --- API ---
API_BASE_URL=http://localhost:8000
CORS_ORIGINS=http://localhost:3000
EOF
    
    echo -e "${GREEN}✓${NC} .env file created"
    echo -e "${YELLOW}⚠${NC} Edit $INSTALL_DIR/.env to add your LICENSE_KEY and Twilio credentials"
else
    echo -e "${GREEN}✓${NC} .env file exists"
fi

# --- Create data directories ---
mkdir -p "$INSTALL_DIR/data" "$INSTALL_DIR/clips" "$INSTALL_DIR/thumbnails"

# --- Build and start ---
echo -e "${YELLOW}⚡${NC} Building Docker images (this may take 5-10 minutes)..."
cd "$INSTALL_DIR"
docker compose build 2>&1 | tail -5

echo -e "${YELLOW}⚡${NC} Starting services..."
docker compose up -d 2>&1

# --- Verify ---
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Spevino LP-OS is installed and running!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════${NC}"
echo ""
echo "  📊 Dashboard:  http://localhost:3000"
echo "  🔧 API Docs:   http://localhost:8000/docs"
echo "  🏪 Data Dir:   $INSTALL_DIR/data"
echo ""
echo "  📧 Test login: owner@example.com / password123"
echo ""
echo -e "${YELLOW}  Next steps:${NC}"
echo "  1. Edit $INSTALL_DIR/.env to add your LICENSE_KEY"
echo "  2. Add your cameras via the dashboard"
echo "  3. Configure detection zones per camera"
echo "  4. Set up Twilio SMS (optional)"
echo ""
echo -e "${BLUE}═══════════════════════════════════════════════${NC}"

# --- License info ---
echo ""
echo -e "${YELLOW}📋 License Status:${NC}"
curl -s http://localhost:8000/license | python3 -m json.tool 2>/dev/null || echo "  (API starting up... check back in a moment)"